#!/bin/bash
# setup.sh - Genera el archivo .env automáticamente si no existe
# Las contraseñas se generan de forma aleatoria en cada instalación

set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo "✅ .env ya existe, no se sobreescribe."
    exit 0
fi

# Generar contraseñas aleatorias seguras
MYSQL_PASS=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 20)
MYSQL_ROOT_PASS=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 20)

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — $(date)

# MySQL Configuration
MYSQL_DATABASE=wordpress
MYSQL_USER=wpuser
MYSQL_PASSWORD=${MYSQL_PASS}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}

# WordPress Configuration
WORDPRESS_DB_HOST=mysql
WORDPRESS_DB_NAME=wordpress
WORDPRESS_DB_USER=wpuser
WORDPRESS_DB_PASSWORD=${MYSQL_PASS}

# Opcional
WORDPRESS_TABLE_PREFIX=wp_
WORDPRESS_DEBUG=false
EOF

chmod 600 "$ENV_FILE"
echo "✅ .env generado con contraseñas aleatorias."
