- hosts: cloud1
  become: yes
  vars:
    remote_project_dir: "/home/{{ ansible_user }}/cloud-1"

  roles:
    - common       # Crear directorios y copiar archivos de configuración
    - docker       # Instalar Docker y Docker Compose
    - firewall     # Configurar UFW (puertos 22, 80, 443)
    - ssl          # Generar certificados SSL autofirmados
    - mysql        # Levantar contenedor MySQL
    - wordpress    # Levantar contenedores WordPress y phpMyAdmin
    - nginx        # Levantar contenedor Nginx (proxy inverso)
